### ISSUE TITLE
docker error An unexpected error occurred: "EINVAL: invalid argument, rmdir '/app/node_modules/.bin'".

### ISSUE THREAD

**Issue by wanglong167** [snibox/snibox#16]
5. Precompile assets:
Starting snibox_database_1 ... done
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.3: The platform "linux" is incompatible with this module.
info "fsevents@1.2.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@rails/webpacker > postcss-cssnext@3.1.0" has unmet peer dependency "caniuse-lite@^1.0.30000697".
warning "@rails/webpacker > webpack-assets-manifest@3.0.1" has unmet peer dependency "webpack-sources@^1.0".
warning " > vue-loader@15.0.7" has unmet peer dependency "css-loader@*".
warning " > webpack-dev-server@3.1.4" has unmet peer dependency "webpack@^4.0.0-beta.1".
warning "webpack-dev-server > webpack-dev-middleware@3.1.3" has unmet peer dependency "webpack@^4.0.0".
error An unexpected error occurred: "EINVAL: invalid argument, rmdir '/app/node_modules/.bin'".
info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Webpacker is installed 🎉 🍰
Using /app/config/webpacker.yml file for setting up webpack paths
Compiling…
Compilation failed:
/usr/local/bundle/bundler/gems/webpacker-d1016cc51c05/lib/webpacker/webpack_runner.rb:11:in `exec': No such file or directory - /app/node_modules/.bin/webpack (Errno::ENOENT)
	from /usr/local/bundle/bundler/gems/webpacker-d1016cc51c05/lib/webpacker/webpack_runner.rb:11:in `block in run'
	from /usr/local/bundle/bundler/gems/webpacker-d1016cc51c05/lib/webpacker/webpack_runner.rb:10:in `chdir'
	from /usr/local/bundle/bundler/gems/webpacker-d1016cc51c05/lib/webpacker/webpack_runner.rb:10:in `run'
	from /usr/local/bundle/bundler/gems/webpacker-d1016cc51c05/lib/webpacker/runner.rb:6:in `run'
	from ./bin/webpack:15:in `<main>'

Done!

**Comment by vavgustov** [comment]
Weird it works good for me.

Try to execute commands below:
```bash
docker-compose run --rm backend yarn install
docker-compose run --rm backend ./bin/rake assets:precompile
```

**Comment by wanglong167** [comment]
Can you save the assets:precompile step?

**Comment by vavgustov** [comment]
No sure what you mean about 'save'. You want screenshot?

**Comment by wanglong167** [comment]
Maybe because of the Great Wall firewall
Can I set the yarn registry?
Docker-compose run --rm backend yarn config set registry https://registry.npm.taobao.org && ./bin/rake assets:precompile
This doesn't seem to work.

**Comment by wanglong167** [comment]
Can the compiled static file be placed directly in the docker?
Cancel assets:precompile this step

**Comment by vavgustov** [comment]
yep it make sense. Compiled assets moved to image and some other improvements added to setup script.

Try now:
```bash
git pull
./bin/docker/setup
```
