### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by laxmanpradhan** [snibox/snibox#17]
Feature request for a search bar. A search bar that will dynamically show results for snips that contain the same characters. Maybe even advanced options that allow search to include body, title, and label, although default behaviour should probably search everything. Thanks!

**Comment by vavgustov** [comment]
Initial search implementation added to the master branch. Demo: https://snibox-demo.herokuapp.com/.

**Comment by laxmanpradhan** [comment]
Would it be possible to add a preview in the search drop down that shows a few words before and after the search term that was matched? Like the summary you see on google search results. So far this looks fantastic!

**Comment by ovizii** [comment]
Can I ask how exactly the search works? If I type "plong" in the demo search field I am immediately shown a snippet called "foooze" labelled "fizz" which contains "plong" in its content. 

However if I type "plong" into the search field and hit enter this snippet is not found.

Is there something wrong here or does the search work differently than I am expecting it to work?
