### ISSUE TITLE
cannot visit resources in packs folder

### ISSUE THREAD

**Issue by anxiaoyi** [snibox/snibox#25]
![2018_07_20_16_07_23](https://user-images.githubusercontent.com/4382796/42991112-3c773d34-8c37-11e8-9939-6a56334ecf4a.png)
![2018_07_20_16_09_23](https://user-images.githubusercontent.com/4382796/42991127-48822f8a-8c37-11e8-92f4-1e68a52b04c6.png)
![2018_07_20_16_09_37](https://user-images.githubusercontent.com/4382796/42991136-505ca1a4-8c37-11e8-9dee-1a22ea820539.png)

**Comment by vavgustov** [comment]
hm.. try to add to .env file: 
```
RAILS_SERVE_STATIC_FILES=true
```

**Comment by anxiaoyi** [comment]
It solved my problem. Thanks @vavgustov
