### ISSUE TITLE
Content is too long

### ISSUE THREAD

**Issue by somedevreally** [snibox/snibox#45]
am user docker version by snowmean/snibox-sqlite

and when i am trying to save large data in a New snippet
it says "Content is too long (maximum is 20000 characters)"
so is it sqlite limitation or snibox's?

thanks

**Comment by vavgustov** [comment]
It's Snibox.

Source: https://github.com/snibox/snibox/blob/f06c0eba941862203026531c27c7009f8d978bfb/app/models/snippet.rb#L9

**Comment by PalmaSolutions** [comment]
It seems that this has been shifted to snippet_file.rb with the latest version. Hope it helps someone.
