### ISSUE TITLE
Multiple files per snippet

### ISSUE THREAD

**Issue by dcalano** [snibox/snibox#6]
This looks nice but it has the same issue I have with GitLab snippets. It only allows for a single bit of code per snippet. I find myself needing to have multiple code pieces per "snippet" a lot of times like how GitHub's gists work.

**Comment by GWillmann** [comment]
Please see https://github.com/snibox/snibox/pull/43#issue-268475071

**Comment by vavgustov** [comment]
https://github.com/snibox/snibox/pull/43 merged!
