### ISSUE TITLE
Error On Deployment in Heroku

### ISSUE THREAD

**Issue by abhay-ranawat** [snibox/snibox#66]
![Screenshot 2019-12-11 at 8 39 38 PM](https://user-images.githubusercontent.com/52895994/70633390-83124800-1c56-11ea-9cee-ccac6edde8f0.png)
App creation failed. Please ensure you have valid values in the above form fields.

**Comment by abhay-ranawat** [comment]
/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:319:in `check_for_activated_spec!': You have already activated bundler 1.17.3, but your Gemfile requires bundler 1.17.2. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
	from /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:31:in `block in setup'
	from /app/vendor/ruby-2.6.1/lib/ruby/2.6.0/forwardable.rb:230:in `each'
	from /app/vendor/ruby-2.6.1/lib/ruby/2.6.0/forwardable.rb:230:in `each'
	from /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:26:in `map'
	from /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:26:in `setup'
	from /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler.rb:107:in `setup'
	from /app/vendor/ruby-2.6.1/lib/ruby/2.6.0/bundler/setup.rb:20:in `<top (required)>'
	from /app/vendor/ruby-2.6.1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /app/vendor/ruby-2.6.1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /app/config/boot.rb:3:in `<top (required)>'
	from /app/bin/rake:2:in `require_relative'
	from /app/bin/rake:2:in `<main>'

**Comment by Adam157** [comment]
Yep, same result here. Deploy to Heroku fails. Log below

<details>
  <summary>Show Log</summary>
  

-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version 12.x...
       Downloading and installing node 12.16.3...
       Using default npm version: 6.14.4
       Resolving yarn version 1.x...
       Downloading and installing yarn (1.22.4)...
       Installed yarn 1.22.4
       
-----> Installing dependencies
       Installing node modules (yarn.lock)
       yarn install v1.22.4
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       warning compression-webpack-plugin@2.0.0: Invalid bin field for "compression-webpack-plugin".
       info fsevents@1.2.9: The platform "linux" is incompatible with this module.
       info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
       [3/4] Linking dependencies...
       warning " > vue-loader@15.7.0" has unmet peer dependency "css-loader@*".
       warning " > vue-loader@15.7.0" has unmet peer dependency "webpack@^4.1.0 || ^5.0.0-0".
       warning " > webpack-dev-server@3.7.1" has unmet peer dependency "webpack@^4.0.0".
       warning "webpack-dev-server > webpack-dev-middleware@3.7.0" has unmet peer dependency "webpack@^4.0.0".
       [4/4] Building fresh packages...
       Done in 39.90s.
       
-----> Build
       
-----> Pruning devDependencies
       yarn install v1.22.4
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       info fsevents@1.2.9: The platform "linux" is incompatible with this module.
       info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
       [3/4] Linking dependencies...
       warning " > vue-loader@15.7.0" has unmet peer dependency "css-loader@*".
       warning " > vue-loader@15.7.0" has unmet peer dependency "webpack@^4.1.0 || ^5.0.0-0".
       warning " > webpack-dev-server@3.7.1" has unmet peer dependency "webpack@^4.0.0".
       warning "webpack-dev-server > webpack-dev-middleware@3.7.0" has unmet peer dependency "webpack@^4.0.0".
       [4/4] Building fresh packages...
       warning Ignored scripts due to flag.
       Done in 7.91s.
       
-----> Caching build
       - yarn cache
       
-----> Build succeeded!
 !     Unmet dependencies don't fail yarn install but may cause runtime issues
       https://github.com/npm/npm/issues/7494
-----> Ruby app detected
-----> Installing bundler 1.17.3
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.6.1
-----> Installing dependencies using bundler 1.17.3
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
       Fetching gem metadata from https://rubygems.org/............
       Fetching rake 12.3.2
       Installing rake 12.3.2
       Fetching concurrent-ruby 1.1.5
       Fetching minitest 5.11.3
       Fetching thread_safe 0.3.6
       Installing minitest 5.11.3
       Installing thread_safe 0.3.6
       Installing concurrent-ruby 1.1.5
       Fetching builder 3.2.3
       Installing builder 3.2.3
       Fetching erubi 1.8.0
       Fetching mini_portile2 2.4.0
       Installing erubi 1.8.0
       Installing mini_portile2 2.4.0
       Fetching crass 1.0.4
       Fetching rack 2.0.7
       Installing crass 1.0.4
       Fetching nio4r 2.3.1
       Installing rack 2.0.7
       Installing nio4r 2.3.1 with native extensions
       Fetching websocket-extensions 0.1.3
       Installing websocket-extensions 0.1.3
       Fetching mini_mime 1.0.1
       Installing mini_mime 1.0.1
       Fetching jsonapi-renderer 0.2.0
       Installing jsonapi-renderer 0.2.0
       Fetching arel 9.0.0
       Installing arel 9.0.0
       Fetching mimemagic 0.3.3
       Fetching bcrypt 3.1.12
       Installing bcrypt 3.1.12 with native extensions
       Installing mimemagic 0.3.3
       Fetching msgpack 1.2.9
       Installing msgpack 1.2.9 with native extensions
       Using bundler 1.17.3
       Fetching orm_adapter 0.5.0
       Installing orm_adapter 0.5.0
       Fetching method_source 0.9.2
       Installing method_source 0.9.2
       Fetching thor 0.20.3
       Installing thor 0.20.3
       Fetching dotenv 2.7.2
       Installing dotenv 2.7.2
       Fetching execjs 2.7.0
       Installing execjs 2.7.0
       Fetching pg 1.1.4
       Installing pg 1.1.4 with native extensions
       Fetching puma 3.12.1
       Installing puma 3.12.1 with native extensions
       Fetching tzinfo 1.2.5
       Installing tzinfo 1.2.5
       Fetching nokogiri 1.10.3
       Installing nokogiri 1.10.3 with native extensions
       Fetching i18n 1.6.0
       Installing i18n 1.6.0
       Fetching websocket-driver 0.7.0
       Installing websocket-driver 0.7.0 with native extensions
       Fetching mail 2.7.1
       Installing mail 2.7.1
       Fetching rack-test 1.1.0
       Installing rack-test 1.1.0
       Fetching warden 1.2.8
       Installing warden 1.2.8
       Fetching rack-proxy 0.6.5
       Installing rack-proxy 0.6.5
       Fetching sprockets 3.7.2
       Installing sprockets 3.7.2
       Fetching marcel 0.3.3
       Installing marcel 0.3.3
       Fetching uglifier 4.1.20
       Installing uglifier 4.1.20
       Fetching bootsnap 1.4.2
       Installing bootsnap 1.4.2 with native extensions
       Fetching activesupport 5.2.3
       Installing activesupport 5.2.3
       Fetching loofah 2.2.3
       Installing loofah 2.2.3
       Fetching rails-dom-testing 2.0.3
       Installing rails-dom-testing 2.0.3
       Fetching globalid 0.4.2
       Installing globalid 0.4.2
       Fetching activemodel 5.2.3
       Fetching case_transform 0.2
       Installing activemodel 5.2.3
       Installing case_transform 0.2
       Fetching rails-html-sanitizer 1.0.4
       Installing rails-html-sanitizer 1.0.4
       Fetching activejob 5.2.3
       Installing activejob 5.2.3
       Fetching actionview 5.2.3
       Installing actionview 5.2.3
       Fetching activerecord 5.2.3
       Installing activerecord 5.2.3
       Fetching actionpack 5.2.3
       Installing actionpack 5.2.3
       Fetching after_commit_action 1.1.0
       Fetching actionmailer 5.2.3
       Fetching actioncable 5.2.3
       Installing after_commit_action 1.1.0
       Installing actioncable 5.2.3
       Installing actionmailer 5.2.3
       Fetching active_model_serializers 0.10.9
       Fetching activestorage 5.2.3
       Fetching railties 5.2.3
       Installing activestorage 5.2.3
       Installing active_model_serializers 0.10.9
       Installing railties 5.2.3
       Fetching sprockets-rails 3.2.1
       Installing sprockets-rails 3.2.1
       Fetching counter_culture 1.12.0
       Installing counter_culture 1.12.0
       Fetching dotenv-rails 2.7.2
       Fetching responders 2.4.1
       Fetching rails 5.2.3
       Installing rails 5.2.3
       Installing dotenv-rails 2.7.2
       Fetching webpacker 4.0.7
       Installing responders 2.4.1
       Installing webpacker 4.0.7
       Fetching devise 4.6.2
       Installing devise 4.6.2
       Bundle complete! 30 Gemfile dependencies, 61 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into `./vendor/bundle`
       Post-install message from i18n:
       
       HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
       But that may break your application.
       
       Please check your Rails app for 'config.i18n.fallbacks = true'.
       If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be
       'config.i18n.fallbacks = [I18n.default_locale]'.
       If not, fallbacks will be broken in your app by I18n 1.1.x.
       
       For more info see:
       https://github.com/svenfuchs/i18n/releases/tag/v1.1.0
       
       Bundle completed (37.72s)
       Cleaning up the bundler cache.
       The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
-----> Detecting rake tasks
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       yarn install v1.22.4
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       warning compression-webpack-plugin@2.0.0: Invalid bin field for "compression-webpack-plugin".
       info fsevents@1.2.9: The platform "linux" is incompatible with this module.
       info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
       [3/4] Linking dependencies...
       warning " > vue-loader@15.7.0" has unmet peer dependency "css-loader@*".
       warning " > vue-loader@15.7.0" has unmet peer dependency "webpack@^4.1.0 || ^5.0.0-0".
       warning " > webpack-dev-server@3.7.1" has unmet peer dependency "webpack@^4.0.0".
       warning "webpack-dev-server > webpack-dev-middleware@3.7.0" has unmet peer dependency "webpack@^4.0.0".
       [4/4] Building fresh packages...
       Done in 43.98s.
       Compiling…
       Compiled all packs in /tmp/build_d40cfcc0a380c41f174a2f26277c7355/public/packs
       Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
       
       Asset precompilation completed (133.02s)
       Cleaning assets
       Running: rake assets:clean
-----> Detecting rails configuration
###### WARNING:
       You set your `config.active_storage.service` to :local in production.
       If you are uploading files to this app, they will not persist after the app
       is restarted, on one-off dynos, or if the app has multiple dynos.
       Heroku applications have an ephemeral file system. To
       persist uploaded files, please use a service such as S3 and update your Rails
       configuration.
       
       For more information can be found in this article:
         https://devcenter.heroku.com/articles/active-storage-on-heroku
       
###### WARNING:
       We detected that some binary dependencies required to
       use all the preview features of Active Storage are not
       present on this system.
       
       For more information please see:
         https://devcenter.heroku.com/articles/active-storage-on-heroku
       
###### WARNING:
       There is a more recent Ruby version available for you to use:
       
       2.6.6
       
       The latest version will include security and bug fixes, we always recommend
       running the latest version of your minor release.
       
       Please upgrade your Ruby version.
       
       For all available Ruby versions see:
         https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
-----> Discovering process types
       Procfile declares types     -> release, web
       Default types for buildpack -> console, rake
-----> Compressing...
       Done: 91.2M
-----> Launching...
 !     Release command declared: this new release will not be available until the command succeeds.
       Released v7
       https://mysnip .herokuapp.com/ deployed to Heroku

</details>

**Comment by mfrischbutter** [comment]
I fixed that by using `ruby 2.7.0p0` and `bundler 2.1.4`, literally the preinstalled version on Ubuntu 20.04 LTS.
Just upgrade your ruby by `rbenv install 2.7.0` and delete your `gemfile.lock`.
After that u have to run `bundle install`.
Push all to master and redeploy.
If the creator wants to, I can make a pull request. Maybe this would mess up a lot and the documentation should be changed also.

For more info you can just lookup my fork, i have done a lot of commits but only last ones count.
https://github.com/mfrischbutter/snibox
Maybe you have to lock `sprockets` to `> 4.0.0`.

Read more about this topic: 
https://devcenter.heroku.com/articles/bundler-version
https://koshigoe.github.io/ruby/2019/02/06/ruby-2.6.1-bundler-1.17.2.html

**Comment by AndreasPantle** [comment]
Is someone able to tell me, what is necessary to deploy this to Heroku without troubles?

**Comment by abhay-ranawat** [comment]
> Is someone able to tell me, what is necessary to deploy this to Heroku without troubles?

Click Here https://heroku.com/deploy?template=https://github.com/mfrischbutter/snibox
