### ISSUE TITLE
"The change you wanted was rejected." - Normal and Docker install.

### ISSUE THREAD

**Issue by lucacastelnuovo** [snibox/snibox#69]
I have followed both the [ubuntu guide](https://snibox.github.io/docs/setup-environment.html#ubuntu) and the [docker guide](https://github.com/snibox/snibox-docker).

After the install there are some CSP issues which can be bypassed by unsetting the CSP header.

Afterwards when I try to signup I get an error message
![Schermafbeelding 2020-02-18 om 18 11 47 PM](https://user-images.githubusercontent.com/26206253/74760361-935c2a00-527a-11ea-9024-1c512a633807.png).

What did I do wrong?

**Comment by lucacastelnuovo** [comment]
I fixed it.

The error was that because of my Apache proxy the origin didn’t meet the set hostname. So the origin header was `http://...` and expected was `https://`.

If you also have this error and need additional info you can send me message.

**Comment by dikkadev** [comment]
Could you explain how exactly you fixed the error?
