### ISSUE TITLE
Demo at Heroku not working

### ISSUE THREAD

**Issue by bauripalash** [snibox/snibox#7]
I opened https://snibox-demo.herokuapp.com
But it didn't open.

![screenshot_2018-07-05-13-42-41](https://user-images.githubusercontent.com/16154204/42310647-94b58ba2-8059-11e8-8031-8d03e2224123.png)

**Comment by vavgustov** [comment]
I just rebuilt demo for Heroku and it should work again. After some time server start to send too big Content-Security-Policy headers to client and Chrome stop working but other browsers worked. I opened #8 for further investigation.

**Comment by bauripalash** [comment]
Working!
